package lex;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int INT = 3;
  public static final int MULT = 10;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int SUB = 9;
  public static final int DIV = 11;
  public static final int ID = 4;
  public static final int ASSIGN = 12;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int SEMICOLON = 13;
  public static final int PRINT = 2;
  public static final int RPAREN = 6;
  public static final int LPAREN = 5;
  public static final int EXPSEQ = 14;
  public static final int STM = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRINT",
  "INT",
  "ID",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "PLUS",
  "SUB",
  "MULT",
  "DIV",
  "ASSIGN",
  "SEMICOLON",
  "EXPSEQ",
  "STM"
  };
}

